## This configuration was generated by `terraform -install-autocomplete`, and
## modified slightly for consistency with the rest of the dotfiles setup.
if command -v terraform > /dev/null 2>&1; then
    if [[ "$BASH_VERSION" ]]; then
        complete -C terraform terraform
    elif [[ "$ZSH_VERSION" ]]; then
        complete -o nospace -C terraform terraform
    fi
fi
